In [1]:
from NetworkSim.simulation.setup.simulator import Simulator
from NetworkSim.architecture.setup.model import Model
from NetworkSim.architecture.base.network import Network

In [2]:
model = Model(network=Network(num_nodes=5))
simulator = Simulator(model=model, until=2000)

In [3]:
simulator.initialise()

In [4]:
simulator.run()

In [5]:
simulator.model.control_ring.packet_record_df

,Timestamp,Raw Packet,Source Node,Destination Node,Status,Total Packet Count
0,157.2,0000000000000100,0,1,added,1
1,157.2,0000010000000100,2,1,added,2
2,157.2,0000011000000100,3,1,added,3
3,157.2,0000100000000100,4,1,added,4
4,159.9,0000001000001000,1,2,added,5
5,277.2,0000000000000100,0,1,removed,4
6,279.9,0000001000001000,1,2,removed,3
7,300.0,0000000000001000,0,2,added,4
8,300.0,0000001000000000,1,0,added,5
9,300.0,0000010000000000,2,0,added,6
10,300.0,0000011000001000,3,2,added,7
11,300.0,0000100000001000,4,2,added,8
12,450.0,0000000000001100,0,3,added,9
13,450.0,0000001000001100,1,3,added,10
14,450.0,0000010000001100,2,3,added,11
15,450.0,0000011000000000,3,0,added,12
16,450.0,0000100000000000,4,0,added,13
17,517.2,0000011000000100,3,1,removed,12
18,540.0,0000000000001000,0,2,removed,11
19,570.0,0000010000001100,2,3,removed,10
20,600.0,0000000000001000,0,2,added,11
21,600.0,0000001000001000,1,2,added,12
22,600.0,0000010000000100,2,1,added,13
23,600.0,0000011000001000,3,2,added,14
24,600.0,0000100000001100,4,3,added,15
25,720.0,0000001000001000,1,2,removed,14
26,750.3,0000000000000100,0,1,added,15
27,750.3,0000001000001100,1,3,added,16
28,750.3,0000010000001100,2,3,added,17
29,750.3,0000011000000100,3,1,added,18
30,810.0,0000000000001100,0,3,removed,17
31,870.3,0000000000000100,0,1,removed,16
32,900.3,0000000000001100,0,3,added,17
33,900.3,0000001000000000,1,0,added,18
34,990.3,0000001000001100,1,3,removed,17
35,1050.3,0000000000001000,0,2,added,18
36,1080.0,0000010000000100,2,1,removed,17
37,1080.0,0000011000001000,3,2,removed,16
38,1200.3,0000000000000100,0,1,added,17
39,1230.3,0000011000000000,3,0,added,18
40,1230.6,0000010000000000,2,0,added,19
41,1237.2,0000010000000100,2,1,removed,18
42,1260.0,0000100000001000,4,2,removed,17
43,1260.3,0000000000001100,0,3,removed,16
44,1350.3,0000001000001000,1,2,added,17
45,1380.3,0000010000000100,2,1,added,18
46,1410.3,0000100000001000,4,2,added,19
47,1440.0,0000000000001000,0,2,removed,18
48,1470.3,0000010000001100,2,3,removed,17
49,1500.3,0000000000001100,0,3,added,18
50,1597.2,0000100000000100,4,1,removed,17
51,1620.6,0000010000001100,2,3,added,18
52,1650.3,0000000000001000,0,2,added,19
53,1680.0,0000100000001100,4,3,removed,18
54,1740.3,0000100000000100,4,1,added,19
55,1770.3,0000100000001000,4,2,removed,18
56,1860.3,0000010000000100,2,1,removed,17
57,1860.3,0000000000001100,0,3,removed,16
58,1950.6,0000100000001100,4,3,added,17

In [6]:
simulator.model.data_rings[0].packet_record_df

,Timestamp,Raw Packet,Source Node,Destination Node,Status,Total Packet Count
0,300.0,1101001110110111110100101001111000011001001010...,0,1,added,1
1,420.0,1101001110110111110100101001111000011001001010...,0,1,removed,0
2,450.0,1111100100000011001101001100010100000111011110...,0,2,added,1
3,600.0,0111001001110100111001001000011110011111010000...,0,3,added,2
4,690.0,1111100100000011001101001100010100000111011110...,0,2,removed,1
5,750.0,0000101011101000010110101110101101111000000010...,0,2,added,2
6,900.0,0111000001001111100100001100111010101011010011...,0,1,added,3
7,960.0,0111001001110100111001001000011110011111010000...,0,3,removed,2
8,1020.0,0111000001001111100100001100111010101011010011...,0,1,removed,1
9,1050.0,1010101010010010110111110000001011001111010100...,0,3,added,2
10,1200.0,0100001001011100000010011001111011110110110110...,0,2,added,3
11,1410.0,1010101010010010110111110000001011001111010100...,0,3,removed,2
12,1500.0,0111110111110010001000111011110100011100011110...,0,1,added,3
13,1590.0,0000101011101000010110101110101101111000000010...,0,2,removed,2
14,1650.0,0011101011000001011011000110110000111010001000...,0,3,added,3
15,1950.0,1010110011111111100001101110110100110110101001...,0,2,added,4