In [1]:
from NetworkSim.simulation.process.ram import RAM
from NetworkSim.simulation.process.transmitter import Transmitter
from NetworkSim.simulation.process.receiver import Receiver
from NetworkSim.architecture.setup.model import Model
from NetworkSim.architecture.base.network import Network
import simpy

In [2]:
env =simpy.Environment()
model = Model(network=Network(num_nodes=5))
ram0 = RAM(env=env, until=2000, ram_id=0, model=model)
ram0.initialise()
trans0 = Transmitter(env=env, ram=ram0, transmitter_id=0, model=model)
trans0.initialise()
rec2 = Receiver(env=env, receiver_id=2, model=model)
rec2.initialise()
rec4 = Receiver(env=env, receiver_id=3, model=model)
rec4.initialise()

In [3]:
env.run(until=2000)

In [4]:
trans0.transmitted_data_packet_df

   Timestamp                                         Raw Packet Destination ID
0      300.0  1110110101110110011000111000011111111000110000...              1
1      450.0  0001000110101000011001001011110111111110111110...              2
2      600.0  1001100111001010011000000001001011111100010101...              3
3      750.0  0001110111001001110011010000000011000000011101...              2
4     1050.0  1111100001011000111010000010111100100000011010...              1
5     1200.0  0001000000110010100111111110101100101111001011...              3
6     1350.0  0010100000010101011001111111010001000001111000...              2
7     1800.0  1000000010011111111111011111101111110101111000...              1
8     1950.0  1101110000110010001100000010111001100111110101...              3

In [5]:
trans0.transmitted_control_packet_df

   Timestamp        Raw Packet Destination ID
0      176.7  0000000000000100              1
1      300.0  0000000000001000              2
2      450.0  0000000000001100              3
3      600.0  0000000000001000              2
4      750.3  0000000000000100              1
5     1050.3  0000000000001100              3
6     1200.3  0000000000001000              2
7     1560.3  0000000000000100              1
8     1800.3  0000000000001100              3

In [6]:
trans0.ram.generated_data_packet_df

,Timestamp,Interarrival to Next,Raw Packet,Destination ID
0,176.430051,298.145377,1110110101110110011000111000011111111000110000...,1
1,180.649276,122.272819,0001000110101000011001001011110111111110111110...,2
2,212.538260,289.206280,1001100111001010011000000001001011111100010101...,3
3,302.922095,212.155360,0001110111001001110011010000000011000000011101...,2
4,474.575427,120.009805,1111100001011000111010000010111100100000011010...,1
5,501.744540,153.398400,0001000000110010100111111110101100101111001011...,3
6,515.077455,180.495574,0010100000010101011001111111010001000001111000...,2
7,594.585232,155.188997,1000000010011111111111011111101111110101111000...,1
8,655.142940,199.983491,1101110000110010001100000010111001100111110101...,3
9,695.573028,177.156883,1001101111001101111011010110100001110001100110...,2
10,749.774229,134.404746,1100101000011101000101010110001100110001100011...,1
11,855.126431,592.004214,1010100011100111011100010101101101011110101001...,3
12,872.729911,159.796989,0010101111000011111110100100010101101110010010...,2
13,884.178975,128.598418,0111001111110111111111011010100010111111111011...,1
14,1012.777393,139.033718,1011111110101000000010010110101110010010010100...,1
15,1032.526900,141.322239,0100101101000011010110110100011000001111101100...,2
16,1151.811111,162.443799,0000100010000100010011101011111101111010000110...,1
17,1173.849139,239.189025,0111011000111001001111010111000001010000100010...,2
18,1314.254910,172.178077,1111001010011011100110001111100100001011001100...,1
19,1372.986281,211.341347,1001111100110101001001110110010110110001101010...,4
20,1413.038164,154.764913,0001111011001111000111100011111101010011100100...,2
21,1447.130645,605.585889,0000110100000111001111001100011010001001011010...,3
22,1486.432987,208.579477,1101110001010110100111111000101011010101000101...,1
23,1567.803077,149.782978,0100110110010111100000100011111111111000001011...,2
24,1584.327627,1570.472224,1101011001100001010010011000111100111100110011...,4
25,1695.012464,176.901184,1110101111111110000110010111010010011001101100...,1
26,1717.586054,240.028494,1110011001111011110110100101111011001110001011...,2
27,1871.913647,273.997808,0101101100110010100001101001100001100011100000...,1
28,1957.614548,205.509234,1011010000101101010110100111001011110110000001...,2

In [7]:
print(trans0.data_clock_cycle)
print(trans0.control_clock_cycle)

150.0
0.3

In [8]:
trans0.model.data_rings[0].packet_record_df

,Timestamp,Raw Packet,Source Node,Destination Node,Status,Total Packet Count
0,300.0,1110110101110110011000111000011111111000110000...,0,1,added,1
1,450.0,0001000110101000011001001011110111111110111110...,0,2,added,2
2,600.0,1001100111001010011000000001001011111100010101...,0,3,added,3
3,690.0,0001000110101000011001001011110111111110111110...,0,2,removed,2
4,750.0,0001110111001001110011010000000011000000011101...,0,2,added,3
5,960.0,1001100111001010011000000001001011111100010101...,0,3,removed,2
6,990.0,0001110111001001110011010000000011000000011101...,0,2,removed,1
7,1050.0,1111100001011000111010000010111100100000011010...,0,1,added,2
8,1200.0,0001000000110010100111111110101100101111001011...,0,3,added,3
9,1350.0,0010100000010101011001111111010001000001111000...,0,2,added,4
10,1560.0,0001000000110010100111111110101100101111001011...,0,3,removed,3
11,1590.0,0010100000010101011001111111010001000001111000...,0,2,removed,2
12,1800.0,1000000010011111111111011111101111110101111000...,0,1,added,3
13,1950.0,1101110000110010001100000010111001100111110101...,0,3,added,4

In [10]:
trans0.model.control_ring.packet_record_df

,Timestamp,Raw Packet,Source Node,Destination Node,Status,Total Packet Count
0,176.7,0000000000000100,0,1,added,1
1,300.0,0000000000001000,0,2,added,2
2,450.0,0000000000001100,0,3,added,3
3,540.0,0000000000001000,0,2,removed,2
4,600.0,0000000000001000,0,2,added,3
5,750.3,0000000000000100,0,1,added,4
6,810.0,0000000000001100,0,3,removed,3
7,840.0,0000000000001000,0,2,removed,2
8,1050.3,0000000000001100,0,3,added,3
9,1200.3,0000000000001000,0,2,added,4
10,1410.3,0000000000001100,0,3,removed,3
11,1440.3,0000000000001000,0,2,removed,2
12,1560.3,0000000000000100,0,1,added,3
13,1800.3,0000000000001100,0,3,added,4

In [13]:
rec2.received_control_packet_df

   Timestamp        Raw Packet Source ID
0      540.0  0000000000001000         0
1      840.0  0000000000001000         0
2     1440.3  0000000000001000         0

In [14]:
rec2.received_data_packet_df

  Timestamp                                         Raw Packet Source ID
0       690  0001000110101000011001001011110111111110111110...         0
1       990  0001110111001001110011010000000011000000011101...         0
2      1590  0010100000010101011001111111010001000001111000...         0